/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    newsletter: Newsletter;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    identity: Identity;
    header: Header;
    footer: Footer;
    socials: Social;
  };
  globalsSelect: {
    identity: IdentitySelect<false> | IdentitySelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero?: {
    /**
     * Optional: replaces page title. You can use <br> for line breaks.
     */
    simpleHeading?: string | null;
  };
  layout: (
    | IconsBoxBlock
    | TitleFigureLongBlock
    | FigureOnTopBlock
    | TitleTextNoBoxingBlock
    | TitleWithSeparatorBlock
    | TextImageContainerBlock
    | BoxedImageBlock
    | PriceListBlock
    | FAQBlock
    | TabsBlock
    | StepperBlock
    | CTABlock
    | FWBannerBlock
    | FWImageBlock
    | BlogPostsGridBlock
    | LogoSliderBlock
    | TicketBoxBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    schema?: {
      /**
       * Select the primary schema type for this page
       */
      type?: ('Article' | 'HowTo' | 'FAQPage' | 'Service' | 'Product' | 'WebPage') | null;
      /**
       * Additional structured data in JSON-LD format
       */
      customData?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Primary keyword for this page
     */
    focusKeyword?: string | null;
    relatedKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Override canonical URL (leave empty to use default)
     */
    canonicalUrl?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconsBoxBlock".
 */
export interface IconsBoxBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  headingLevel: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  noBoxing?: ('withBoxing' | 'noBoxing') | null;
  center?: boolean | null;
  items: {
    /**
     * Click to select an icon from the visual picker
     */
    icon: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconsBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleFigureLongBlock".
 */
export interface TitleFigureLongBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  noBoxing?: ('withBoxing' | 'noBoxing') | null;
  headingLevel: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  items: {
    /**
     * The number displayed in the span (e.g., "01", "02", "03")
     */
    figure: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'titleFigureLong';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FigureOnTopBlock".
 */
export interface FigureOnTopBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  noBoxing?: ('withBoxing' | 'noBoxing') | null;
  headingLevel: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  center?: boolean | null;
  items: {
    /**
     * Free text to display in the figure element
     */
    figure: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'figureOnTop';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleTextNoBoxingBlock".
 */
export interface TitleTextNoBoxingBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  headingLevel: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  center?: boolean | null;
  title: string;
  text: string;
  ctaText?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'titleTextNoBoxing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithSeparatorBlock".
 */
export interface TitleWithSeparatorBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  noBoxing?: ('withBoxing' | 'noBoxing') | null;
  headingLevel: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  center?: boolean | null;
  items: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'titleWithSeparator';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageContainerBlock".
 */
export interface TextImageContainerBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  textColumnWidth: 'col-lg-4' | 'col-lg-6' | 'col-lg-8';
  image: number | Media;
  layout: 'textImage' | 'imageText';
  headingLevel: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  center?: boolean | null;
  title: string;
  text: string;
  ctaText?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textImageContainer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoxedImageBlock".
 */
export interface BoxedImageBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  height: 'normal' | 'large' | 'superlarge';
  backgroundImage: number | Media;
  overlayOpacity?: ('overlay-opacity-0' | 'overlay-opacity-10' | 'overlay-opacity-25' | 'overlay-opacity-50') | null;
  quoteTag: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  quote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'boxedImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PriceListBlock".
 */
export interface PriceListBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  items: {
    thumbnailImage: number | Media;
    category: string;
    titleTag: 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
    title: string;
    price: string;
    /**
     * Optional unit or period to display after the price (will appear in superscript)
     */
    priceUnit?: string | null;
    description: string;
    features: {
      feature: string;
      id?: string | null;
    }[];
    ctaText: string;
    ctaUrl: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'priceList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  backgroundColor?: ('bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5') | null;
  /**
   * Optional title for the FAQ section
   */
  faqTitle?: string | null;
  /**
   * Select the HTML tag for the FAQ title
   */
  titleTag: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  /**
   * Optional introduction text for the FAQ section
   */
  faqText?: string | null;
  items: {
    question: string;
    questionTag: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlock".
 */
export interface TabsBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  tabsWidth: 'col-lg-6' | 'col-lg-9' | 'col-lg-12';
  image?: (number | null) | Media;
  layout?: ('tabsImage' | 'imageTabs') | null;
  overlayOpacity?: ('overlay-opacity-0' | 'overlay-opacity-10' | 'overlay-opacity-25' | 'overlay-opacity-50') | null;
  items: {
    title: string;
    content: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepperBlock".
 */
export interface StepperBlock {
  centered?: boolean | null;
  image: number | Media;
  stepperWidth: '8' | '6';
  stepperPosition: 'left' | 'right';
  layoutElements:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  finalScreen?: {
    /**
     * Click to select an icon from the visual picker
     */
    icon?: string | null;
    message?: string | null;
    /**
     * Laissez vide pour ne pas afficher de bouton
     */
    buttonText?: string | null;
    /**
     * Le bouton ne s'affichera que si le texte ET l'URL sont renseignés
     */
    buttonUrl?: string | null;
  };
  steps?:
    | {
        title: string;
        description?: string | null;
        contentType: 'text' | 'form' | 'formBuilder';
        content?: string | null;
        form?: (number | null) | Form;
        /**
         * Construisez votre formulaire en ajoutant des champs ci-dessous
         */
        fields?:
          | (
              | {
                  name: string;
                  label: string;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'text';
                }
              | {
                  name: string;
                  label: string;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'email';
                }
              | {
                  name: string;
                  label: string;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textarea';
                }
              | {
                  name: string;
                  label: string;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'number';
                }
              | {
                  name: string;
                  label: string;
                  required?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'checkbox';
                }
              | {
                  /**
                   * Laissez vide pour générer automatiquement depuis le label
                   */
                  name?: string | null;
                  label?: string | null;
                  required?: boolean | null;
                  allowMultiple?: boolean | null;
                  options?:
                    | {
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'select';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stepper';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            /**
             * Allow users to select multiple options
             */
            allowMultiple?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  alignment: 'left' | 'center' | 'right';
  buttons: {
    text: string;
    url: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FWBannerBlock".
 */
export interface FWBannerBlock {
  height: 'normal' | 'large' | 'superlarge';
  titleTag: 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  title: string;
  description: string;
  ctaText?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fwBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FWImageBlock".
 */
export interface FWImageBlock {
  height: 'small' | 'normal' | 'large' | 'extralarge';
  backgroundImage: number | Media;
  quoteTag: 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span' | 'p';
  quote: string;
  overlayOpacity?: ('overlay-opacity-0' | 'overlay-opacity-10' | 'overlay-opacity-25' | 'overlay-opacity-50') | null;
  enableParallax?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fwImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPostsGridBlock".
 */
export interface BlogPostsGridBlock {
  /**
   * Titre affiché au-dessus de la grille de posts
   */
  title?: string | null;
  centerTitle?: boolean | null;
  /**
   * Choisissez le format d'affichage des posts
   */
  layout: 'normal' | 'oneCol';
  /**
   * Laisser vide pour afficher tous les posts
   */
  category?: (number | null) | Category;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogPostsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoSliderBlock".
 */
export interface LogoSliderBlock {
  /**
   * Hauteur maximale des logos entre 30px et 80px
   */
  imageMaxHeight: number;
  scrollSpeed: 'fast' | 'normal' | 'slow';
  /**
   * Add logos to display in the slider. Logos will automatically scroll and duplicate for infinite loop effect.
   */
  logos: {
    /**
     * Upload a logo image (PNG, SVG, or JPG)
     */
    logo: number | Media;
    /**
     * Alternative text for the logo (for accessibility)
     */
    alt: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TicketBoxBlock".
 */
export interface TicketBoxBlock {
  backgroundColor?: ('bg-primary' | 'bg-green' | 'bg-ivory') | null;
  paddingTop?: ('pt-0' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6') | null;
  paddingBottom?: ('pb-0' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6') | null;
  /**
   * Choose alignment when displaying only one ticket
   */
  alignment?: ('left' | 'center' | 'right') | null;
  /**
   * Add 1 or 2 tickets (call-to-action cards)
   */
  tickets: {
    /**
     * Click to select an icon from the visual picker
     */
    icon: string;
    /**
     * Main text displayed in the ticket
     */
    text: string;
    /**
     * URL for the ticket link (e.g., /contact or https://example.com)
     */
    link: string;
    /**
     * Text displayed on the button
     */
    linkText: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'ticketBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Texte affiché au-dessus des articles connexes en bas de page
   */
  relatedPostsTitle?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  email: string;
  status: 'active' | 'unsubscribed';
  subscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        simpleHeading?: T;
      };
  layout?:
    | T
    | {
        iconsBox?: T | IconsBoxBlockSelect<T>;
        titleFigureLong?: T | TitleFigureLongBlockSelect<T>;
        figureOnTop?: T | FigureOnTopBlockSelect<T>;
        titleTextNoBoxing?: T | TitleTextNoBoxingBlockSelect<T>;
        titleWithSeparator?: T | TitleWithSeparatorBlockSelect<T>;
        textImageContainer?: T | TextImageContainerBlockSelect<T>;
        boxedImage?: T | BoxedImageBlockSelect<T>;
        priceList?: T | PriceListBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        tabs?: T | TabsBlockSelect<T>;
        stepper?: T | StepperBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        fwBanner?: T | FWBannerBlockSelect<T>;
        fwImage?: T | FWImageBlockSelect<T>;
        blogPostsGrid?: T | BlogPostsGridBlockSelect<T>;
        logoSlider?: T | LogoSliderBlockSelect<T>;
        ticketBox?: T | TicketBoxBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        schema?:
          | T
          | {
              type?: T;
              customData?: T;
            };
        focusKeyword?: T;
        relatedKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconsBoxBlock_select".
 */
export interface IconsBoxBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  headingLevel?: T;
  noBoxing?: T;
  center?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleFigureLongBlock_select".
 */
export interface TitleFigureLongBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  noBoxing?: T;
  headingLevel?: T;
  items?:
    | T
    | {
        figure?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FigureOnTopBlock_select".
 */
export interface FigureOnTopBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  noBoxing?: T;
  headingLevel?: T;
  center?: T;
  items?:
    | T
    | {
        figure?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleTextNoBoxingBlock_select".
 */
export interface TitleTextNoBoxingBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  headingLevel?: T;
  center?: T;
  title?: T;
  text?: T;
  ctaText?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithSeparatorBlock_select".
 */
export interface TitleWithSeparatorBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  noBoxing?: T;
  headingLevel?: T;
  center?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageContainerBlock_select".
 */
export interface TextImageContainerBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  textColumnWidth?: T;
  image?: T;
  layout?: T;
  headingLevel?: T;
  center?: T;
  title?: T;
  text?: T;
  ctaText?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoxedImageBlock_select".
 */
export interface BoxedImageBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  height?: T;
  backgroundImage?: T;
  overlayOpacity?: T;
  quoteTag?: T;
  quote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PriceListBlock_select".
 */
export interface PriceListBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  items?:
    | T
    | {
        thumbnailImage?: T;
        category?: T;
        titleTag?: T;
        title?: T;
        price?: T;
        priceUnit?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        ctaText?: T;
        ctaUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  faqTitle?: T;
  titleTag?: T;
  faqText?: T;
  items?:
    | T
    | {
        question?: T;
        questionTag?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlock_select".
 */
export interface TabsBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  tabsWidth?: T;
  image?: T;
  layout?: T;
  overlayOpacity?: T;
  items?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepperBlock_select".
 */
export interface StepperBlockSelect<T extends boolean = true> {
  centered?: T;
  image?: T;
  stepperWidth?: T;
  stepperPosition?: T;
  layoutElements?: T;
  finalScreen?:
    | T
    | {
        icon?: T;
        message?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        contentType?: T;
        content?: T;
        form?: T;
        fields?:
          | T
          | {
              text?:
                | T
                | {
                    name?: T;
                    label?: T;
                    required?: T;
                    id?: T;
                    blockName?: T;
                  };
              email?:
                | T
                | {
                    name?: T;
                    label?: T;
                    required?: T;
                    id?: T;
                    blockName?: T;
                  };
              textarea?:
                | T
                | {
                    name?: T;
                    label?: T;
                    required?: T;
                    id?: T;
                    blockName?: T;
                  };
              number?:
                | T
                | {
                    name?: T;
                    label?: T;
                    required?: T;
                    id?: T;
                    blockName?: T;
                  };
              checkbox?:
                | T
                | {
                    name?: T;
                    label?: T;
                    required?: T;
                    id?: T;
                    blockName?: T;
                  };
              select?:
                | T
                | {
                    name?: T;
                    label?: T;
                    required?: T;
                    allowMultiple?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  alignment?: T;
  buttons?:
    | T
    | {
        text?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FWBannerBlock_select".
 */
export interface FWBannerBlockSelect<T extends boolean = true> {
  height?: T;
  titleTag?: T;
  title?: T;
  description?: T;
  ctaText?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FWImageBlock_select".
 */
export interface FWImageBlockSelect<T extends boolean = true> {
  height?: T;
  backgroundImage?: T;
  quoteTag?: T;
  quote?: T;
  overlayOpacity?: T;
  enableParallax?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPostsGridBlock_select".
 */
export interface BlogPostsGridBlockSelect<T extends boolean = true> {
  title?: T;
  centerTitle?: T;
  layout?: T;
  category?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoSliderBlock_select".
 */
export interface LogoSliderBlockSelect<T extends boolean = true> {
  imageMaxHeight?: T;
  scrollSpeed?: T;
  logos?:
    | T
    | {
        logo?: T;
        alt?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TicketBoxBlock_select".
 */
export interface TicketBoxBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  alignment?: T;
  tickets?:
    | T
    | {
        icon?: T;
        text?: T;
        link?: T;
        linkText?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  relatedPostsTitle?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  subscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              allowMultiple?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  /**
   * Logo principal du site (utilisé dans le header et footer)
   */
  logo: number | Media;
  /**
   * Nom de votre entreprise/site
   */
  siteName: string;
  /**
   * Slogan ou description courte de votre activité
   */
  slogan: string;
  address: {
    /**
     * Numéro et nom de rue
     */
    street?: string | null;
    /**
     * Bâtiment, étage, etc.
     */
    additionalInfo?: string | null;
    postalCode?: string | null;
    city: string;
    region?: string | null;
    country: string;
  };
  /**
   * Format: +33 1 23 45 67 89
   */
  phone?: string | null;
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  banner?: {
    enabled?: boolean | null;
    /**
     * Cliquez pour sélectionner une icône
     */
    icon?: string | null;
    /**
     * Maximum 100 caractères, espaces compris
     */
    text?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
    /**
     * Laisser à 0 pour désactiver la fermeture automatique
     */
    autoCloseAfter?: number | null;
    /**
     * Laisser vide pour afficher immédiatement
     */
    startDate?: string | null;
    /**
     * Laisser vide pour afficher indéfiniment
     */
    endDate?: string | null;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        hasMegaMenu?: boolean | null;
        megaMenuSlots?:
          | {
              title: string;
              links?:
                | {
                    /**
                     * Click to select an icon from the visual picker
                     */
                    icon: string;
                    label: string;
                    /**
                     * Short description (max 90 characters including spaces)
                     */
                    description: string;
                    url: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Select a post to feature in the 4th slot of the mega menu
         */
        featuredPost?: (number | null) | Post;
        id?: string | null;
      }[]
    | null;
  ctaButton1?: {
    text?: string | null;
    url?: string | null;
  };
  ctaButton2?: {
    text?: string | null;
    url?: string | null;
  };
  ctaButton3?: {
    text?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Maximum 4 colonnes de liens pour le footer
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Liens légaux affichés en bas du footer (RGPD, CGU, Mentions légales...)
   */
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: number;
  /**
   * URL de votre page Facebook
   */
  facebook?: string | null;
  /**
   * URL de votre profil Twitter/X
   */
  twitter?: string | null;
  /**
   * URL de votre profil Instagram
   */
  instagram?: string | null;
  /**
   * URL de votre page LinkedIn
   */
  linkedin?: string | null;
  /**
   * URL de votre chaîne YouTube
   */
  youtube?: string | null;
  /**
   * URL de votre profil TikTok
   */
  tiktok?: string | null;
  /**
   * Lien WhatsApp (format: https://wa.me/numero)
   */
  whatsapp?: string | null;
  /**
   * URL de votre serveur Discord
   */
  discord?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  logo?: T;
  siteName?: T;
  slogan?: T;
  address?:
    | T
    | {
        street?: T;
        additionalInfo?: T;
        postalCode?: T;
        city?: T;
        region?: T;
        country?: T;
      };
  phone?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  banner?:
    | T
    | {
        enabled?: T;
        icon?: T;
        text?: T;
        buttonText?: T;
        buttonUrl?: T;
        autoCloseAfter?: T;
        startDate?: T;
        endDate?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        hasMegaMenu?: T;
        megaMenuSlots?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    description?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        featuredPost?: T;
        id?: T;
      };
  ctaButton1?:
    | T
    | {
        text?: T;
        url?: T;
      };
  ctaButton2?:
    | T
    | {
        text?: T;
        url?: T;
      };
  ctaButton3?:
    | T
    | {
        text?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  facebook?: T;
  twitter?: T;
  instagram?: T;
  linkedin?: T;
  youtube?: T;
  tiktok?: T;
  whatsapp?: T;
  discord?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColoredQuoteBlock".
 */
export interface ColoredQuoteBlock {
  quote: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'coloredQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  position?: ('default' | 'fullWidth') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language:
    | 'javascript'
    | 'typescript'
    | 'python'
    | 'java'
    | 'cpp'
    | 'csharp'
    | 'php'
    | 'ruby'
    | 'go'
    | 'rust'
    | 'css'
    | 'html'
    | 'json'
    | 'markdown'
    | 'bash'
    | 'sql';
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}